// /method view model (docs/phases/P6.md §3, §5, step 7). Every figure comes from the
// build-time backtest summary. The report itself renders only inside ReportFrame
// (components/method/report-frame.tsx), under a provenance heading and this preface.
import { backtest, type BacktestSummary, type WinRateBucket } from "./backtest";
import { formatCount, formatSeasonRange } from "./format";

/** Break-even share of decided games at the standard −110 price: risk 110 to win 100,
 *  so a side has to win 110 of every 210. */
export const BREAKEVEN_110 = 110 / 210;

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const bucketLabel = (b: WinRateBucket) => `${b.market}, ${b.bucket} pt |edge|, ${formatCount(b.decided)} decided`;

/** Exact P(Binomial(n, ½) ≥ k): the chance a side that wins half its games still reaches
 *  k wins in n. n is a few hundred at most, so a direct sum is fine. */
export function coinFlipTail(n: number, k: number): number {
  let logPmf = -n * Math.LN2; // log P(0 wins)
  let tail = 0;
  for (let j = 0; j <= n; j++) {
    if (j >= k) tail += Math.exp(logPmf);
    if (j < n) logPmf += Math.log((n - j) / (j + 1));
  }
  return tail;
}

/** How a bucket at or above break-even compares with a coin flip: points above 50%, the
 *  binomial standard error at 50% for its decided games, and the distance in SEs. */
export function againstCoinFlip(b: WinRateBucket): { points: number; se: number; z: number } {
  const share = b.wins / b.decided;
  const se = Math.sqrt(0.25 / b.decided);
  return { points: (share - 0.5) * 100, se: se * 100, z: (share - 0.5) / se };
}

/** Across every bucket, if the model's side won exactly half the time: the expected number
 *  at or above break-even, and the chance at least one is. Buckets treated as independent;
 *  spread and total buckets share games, so it's approximate. */
export function chanceAtOrAbove(buckets: WinRateBucket[]): { expected: number; atLeastOne: number } {
  const ps = buckets.map((b) => coinFlipTail(b.decided, Math.ceil(b.decided * BREAKEVEN_110 - 1e-9)));
  return {
    expected: ps.reduce((a, p) => a + p, 0),
    atLeastOne: 1 - ps.reduce((a, p) => a * (1 - p), 1),
  };
}

function atOrAboveVerdict(atOrAbove: WinRateBucket[], all: WinRateBucket[], breakeven: string): string {
  const n = atOrAbove.length;
  const listed = atOrAbove
    .map((b) => `${pct(b.rate)} (${b.market}, ${b.bucket} pt |edge|, ${formatCount(b.wins)} of ${formatCount(b.decided)} decided)`)
    .join("; ");
  const margins = atOrAbove.map((b) => {
    const { points, se, z } = againstCoinFlip(b);
    const verdict =
      z < 1
        ? "far too few games to tell it apart from chance"
        : z < 1.96
          ? "too few games to tell it apart from chance"
          : "unlikely at a true 50% on its own, though the count below still applies";
    const subject = n === 1 ? "That's" : `${pct(b.rate)} (${b.market}, ${b.bucket} pt) is`;
    return (
      `${subject} ${points.toFixed(1)} points above a coin flip. With ${formatCount(b.decided)} decided ` +
      `games, the standard error of that share is ${se.toFixed(1)} points, so it sits ${z.toFixed(1)} ` +
      `standard errors above 50%: ${verdict}.`
    );
  });
  const { expected, atLeastOne } = chanceAtOrAbove(all);
  return [
    `${n} of ${all.length} buckets ${n === 1 ? "reaches" : "reach"} it: ${listed}.`,
    ...margins,
    `${n === 1 ? "It's" : "They're"} also ${n} of ${all.length} buckets examined. If the model's side won ` +
      `exactly half the time, about ${Math.round(expected)} of ${all.length} would reach ${breakeven} by ` +
      `chance, and at least one would do so about ${Math.round(atLeastOne * 100)}% of the time.`,
    "Every bucket is shown, and the correlations above are the test.",
  ].join(" ");
}

export interface ReportFrameView {
  heading: string;
  breakeven: string; // "52.4%"
  highest: WinRateBucket;
  atOrAbove: WinRateBucket[]; // buckets at or above break-even (p5-v2: spread 2–3 pt only)
  preface: string[]; // app-authored sentences, in order
}

export function reportFrameView(s: BacktestSummary = backtest): ReportFrameView {
  if (s.win_rates.length === 0) throw new Error("backtest summary has no win-rate buckets");
  const highest = s.win_rates.reduce((a, b) => (b.rate > a.rate ? b : a));
  const atOrAbove = s.win_rates.filter((b) => b.rate >= BREAKEVEN_110);
  const breakeven = pct(BREAKEVEN_110);
  const verdict =
    atOrAbove.length === 0
      ? `No bucket reaches it. The highest is ${pct(highest.rate)} (${bucketLabel(highest)}).`
      : atOrAboveVerdict(atOrAbove, s.win_rates, breakeven);
  return {
    heading:
      `Backtest report — generated by ${s.report.script}, ${s.report.generated_utc} UTC, ` +
      `from ${formatCount(s.n_games)} out-of-sample games`,
    breakeven,
    highest,
    atOrAbove,
    preface: [
      `Below is the backtest report exactly as ${s.report.script} wrote it.`,
      `Its two tables by |edge| are backtest win rates: how often the model's side of the ` +
        `closing line won, ${formatSeasonRange(s.test_seasons)}.`,
      `At the standard −110 price, a side has to win ${breakeven} of decided games to break ` +
        `even (110 ÷ 210). ${verdict}`,
      "These rates are evidence that the edge doesn't work. They are not a record of anything this site has done.",
    ],
  };
}
