// /method view model (docs/phases/P6.md §3, §5, step 7). Every figure comes from the
// build-time backtest summary. The report itself renders only inside ReportFrame
// (components/method/report-frame.tsx), under a provenance heading and this preface.
import { backtest, type BacktestSummary, type WinRateBucket } from "./backtest";
import { formatCount, formatSeasonRange } from "./format";

/** Break-even share of decided games at the standard −110 price: risk 110 to win 100,
 *  so a side has to win 110 of every 210. */
export const BREAKEVEN_110 = 110 / 210;

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const bucketLabel = (b: WinRateBucket) => `${b.market}, ${b.bucket} pt |edge|, ${formatCount(b.decided)} decided`;

export interface ReportFrameView {
  heading: string;
  breakeven: string; // "52.4%"
  highest: WinRateBucket;
  atOrAbove: WinRateBucket[]; // buckets at or above break-even (none today)
  preface: string[]; // app-authored sentences, in order
}

export function reportFrameView(s: BacktestSummary = backtest): ReportFrameView {
  if (s.win_rates.length === 0) throw new Error("backtest summary has no win-rate buckets");
  const highest = s.win_rates.reduce((a, b) => (b.rate > a.rate ? b : a));
  const atOrAbove = s.win_rates.filter((b) => b.rate >= BREAKEVEN_110);
  const breakeven = pct(BREAKEVEN_110);
  const verdict =
    atOrAbove.length === 0
      ? `No bucket reaches it. The highest is ${pct(highest.rate)} (${bucketLabel(highest)}).`
      : `${atOrAbove.length} of ${s.win_rates.length} buckets reach it: ` +
        `${atOrAbove.map((b) => `${pct(b.rate)} (${bucketLabel(b)})`).join("; ")}. ` +
        "Every bucket is shown, and the correlations above are the test.";
  return {
    heading:
      `Backtest report — generated by ${s.report.script}, ${s.report.generated_utc} UTC, ` +
      `from ${formatCount(s.n_games)} out-of-sample games`,
    breakeven,
    highest,
    atOrAbove,
    preface: [
      `Below is the backtest report exactly as ${s.report.script} wrote it.`,
      `Its two tables by |edge| are backtest win rates: how often the model's side of the ` +
        `closing line won, ${formatSeasonRange(s.test_seasons)}.`,
      `At the standard −110 price, a side has to win ${breakeven} of decided games to break ` +
        `even (110 ÷ 210). ${verdict}`,
      "These rates are evidence that the edge doesn't work. They are not a record of anything this site has done.",
    ],
  };
}
