// Pure parsing for the build-time backtest summary (docs/phases/P6.md §3, §5, step 4).
// No I/O here: sync-content.mjs reads the files, and tests/backtest-content.test.ts
// runs this against the real report.
//
// Every lookup is by exact heading and column name, never by position. Anything
// unexpected (a missing or duplicated heading, a renamed column, a non-numeric cell,
// or the report and the coefficients file disagreeing) throws, which fails the build.
// A status line built from a misread table is worse than no build.

export class ContentError extends Error {
  name = "ContentError";
}

/**
 * The markdown table directly under a unique heading line.
 * @param {string} md
 * @param {string} heading exact heading line, e.g. "### Margin (home − away)"
 * @returns {Record<string, string>[]} rows keyed by header cell
 */
export function tableUnder(md, heading) {
  const lines = md.split(/\r?\n/);
  const at = lines.flatMap((l, i) => (l.trim() === heading ? [i] : []));
  if (at.length !== 1) {
    throw new ContentError(`expected exactly one "${heading}" in the report, found ${at.length}`);
  }
  let i = at[0] + 1;
  while (i < lines.length && !lines[i].trim().startsWith("|")) {
    if (/^#{1,6} /.test(lines[i])) break; // next heading before any table
    i++;
  }
  const rows = [];
  while (i < lines.length && lines[i].trim().startsWith("|")) rows.push(lines[i++]);
  if (rows.length < 3) throw new ContentError(`no table under "${heading}"`);
  // Split on unescaped pipes only; "\|" is a literal pipe inside a cell.
  const cells = (l) =>
    l
      .trim()
      .replace(/^\|/, "")
      .replace(/(?<!\\)\|$/, "")
      .split(/(?<!\\)\|/)
      .map((c) => c.trim().replace(/\\\|/g, "|"));
  const header = cells(rows[0]);
  return rows.slice(2).map((r) => {
    const c = cells(r);
    if (c.length !== header.length) {
      throw new ContentError(`ragged row under "${heading}": ${r}`);
    }
    return Object.fromEntries(header.map((h, k) => [h, c[k]]));
  });
}

/** @param {Record<string, string>[]} rows */
function rowWhere(rows, column, value, heading) {
  if (!rows.length || !(column in rows[0])) {
    throw new ContentError(`no "${column}" column under "${heading}"`);
  }
  const hit = rows.filter((r) => r[column] === value);
  if (hit.length !== 1) {
    throw new ContentError(`expected one "${value}" row under "${heading}", found ${hit.length}`);
  }
  return hit[0];
}

/** @param {Record<string, string>} row */
function number(row, column, heading) {
  if (!(column in row)) throw new ContentError(`no "${column}" column under "${heading}"`);
  const raw = row[column].replace(/−/g, "-");
  if (!/^-?\d+(\.\d+)?$/.test(raw)) {
    throw new ContentError(`"${column}" under "${heading}" is not a number: ${row[column]}`);
  }
  return Number(raw);
}

/** "[-0.080, 0.016]" → [-0.08, 0.016] */
function interval(row, column, heading) {
  const m = /^\[(-?\d+(?:\.\d+)?), (-?\d+(?:\.\d+)?)\]$/.exec(
    (row[column] ?? "").replace(/−/g, "-"),
  );
  if (!m) throw new ContentError(`"${column}" under "${heading}" is not an interval`);
  return [Number(m[1]), Number(m[2])];
}

const MARGIN = "### Margin (home − away)";
const SPREAD_CORR = "### Spread: correlation";
const SPREAD_PICKS = "### Spread picks by |edge| (ATS vs. close)";
const TOTAL_PICKS = "### Total picks by |edge| (O/U vs. close)";

// scripts/backtest.py writes absolute-value bars bare inside three table headers ("|edge|
// pts" twice, "Per-game |Δ projection|" once), which splits each header into extra cells,
// so neither GFM nor tableUnder reads those tables. Escaping the bars changes the
// markdown, not the text: the rendered cells still read "|edge| pts". Only these exact
// header prefixes are touched; renderReport's table count fails the build on any other
// malformed table.
const BARE_HEADERS = [
  ["| |edge| pts |", "| \\|edge\\| pts |"],
  ["| Per-game |Δ projection| |", "| Per-game \\|Δ projection\\| |"],
];

/** @param {string} md */
export function escapeReportTables(md) {
  return md
    .split(/\r?\n/)
    .map((l) => {
      const hit = BARE_HEADERS.find(([bare]) => l.startsWith(bare));
      return hit ? hit[1] + l.slice(hit[0].length) : l;
    })
    .join("\n");
}

/**
 * Where the report came from, from its own "Generated by" line.
 * @param {string} md
 * @returns {{ script: string, generated_utc: string }}
 */
export function reportProvenance(md) {
  const m = /^Generated by `uv run python (scripts\/backtest\.py)` on (\d{4}-\d{2}-\d{2} \d{2}:\d{2}) \(UTC\)\.$/m.exec(md);
  if (!m?.[1] || !m[2]) throw new ContentError('no "Generated by `uv run python scripts/backtest.py` on <date> (UTC)." line');
  return { script: m[1], generated_utc: m[2] };
}

/**
 * The backtest win-rate tables by |edge| bucket. The report's own "Win rate" column,
 * cross-checked against Wins / Decided.
 * @param {string} md
 */
export function winRateBuckets(md) {
  const fixed = escapeReportTables(md);
  /** @type {{market: string, bucket: string, decided: number, wins: number, rate: number}[]} */
  const out = [];
  /** @type {[string, string][]} */
  const tables = [["spread", SPREAD_PICKS], ["total", TOTAL_PICKS]];
  for (const [market, heading] of tables) {
    for (const r of tableUnder(fixed, heading)) {
      const bucket = r["|edge| pts"];
      if (bucket === undefined) throw new ContentError(`no "|edge| pts" column under "${heading}"`);
      const decided = number(r, "Decided", heading);
      const wins = number(r, "Wins", heading);
      const rate = number(r, "Win rate", heading);
      if (!(decided > 0) || Math.abs(wins / decided - rate) > 0.0006) {
        throw new ContentError(`"Win rate" ${rate} under "${heading}" isn't Wins/Decided (${wins}/${decided})`);
      }
      out.push({ market, bucket, decided, wins, rate });
    }
  }
  return out;
}

/**
 * The report as HTML, verbatim: headings demoted two levels (the page and the frame own
 * h1/h2), and tables wrapped for horizontal scroll. Throws if any table in the source
 * fails to parse as a table, so a malformed table can't render as a paragraph of pipes.
 * @param {string} md
 * @param {typeof import("marked").Marked} Marked
 */
export function renderReport(md, Marked) {
  const fixed = escapeReportTables(md);
  const separators = fixed.split("\n").filter((l) => /^\|(\s*:?-{3,}:?\s*\|)+\s*$/.test(l.trim())).length;
  let tables = 0;
  const marked = new Marked({
    gfm: true,
    async: false,
    walkTokens(t) {
      if (t.type === "table") tables++;
      if (t.type === "heading") t.depth = Math.min(6, t.depth + 2);
    },
  });
  const html = /** @type {string} */ (marked.parse(fixed));
  if (tables !== separators) {
    throw new ContentError(`report has ${separators} table separators but ${tables} parsed tables`);
  }
  return html
    .replace(/<table>/g, '<div class="table-scroll"><table class="data report-table">')
    .replace(/<\/table>/g, "</table></div>");
}

/**
 * Build the summary the app renders. Cross-checks the report against the
 * coefficients file, since both come from the same run.
 * @param {string} reportMd docs/backtest_report.md
 * @param {any} coefficients pipeline/synthesis/model_coefficients.json
 */
export function buildSummary(reportMd, coefficients) {
  const margin = tableUnder(reportMd, MARGIN);
  const all = rowWhere(margin, "Season", "**All**", MARGIN);
  const seasons = margin
    .filter((r) => /^\d{4}$/.test(r.Season))
    .map((r) => Number(r.Season));

  const corr = tableUnder(reportMd, SPREAD_CORR);
  const corrAll = rowWhere(corr, "Slice", "All", SPREAD_CORR);
  const validatedCell = corrAll.Validated;
  if (validatedCell !== "yes" && validatedCell !== "no") {
    throw new ContentError(`"Validated" under "${SPREAD_CORR}" is "${validatedCell}"`);
  }

  const cal = coefficients?.calibration;
  if (!cal || !Array.isArray(cal.test_seasons) || typeof cal.n_games !== "number") {
    throw new ContentError("model_coefficients.json has no calibration block");
  }
  const n = number(all, "n", MARGIN);
  const checks = [
    [n === cal.n_games, `margin n ${n} vs calibration.n_games ${cal.n_games}`],
    [number(all, "Close n", MARGIN) === n, "margin Close n differs from n"],
    [number(corrAll, "n", SPREAD_CORR) === n, "spread-correlation n differs from margin n"],
    [
      JSON.stringify(seasons) === JSON.stringify(cal.test_seasons),
      `report seasons ${seasons} vs calibration.test_seasons ${cal.test_seasons}`,
    ],
  ];
  for (const [ok, what] of checks) {
    if (!ok) throw new ContentError(`report and coefficients disagree: ${what}`);
  }

  /** @type {Record<string, {n_games: number, stability_range: number[], margin_sd: number, spread: any, total: any}>} */
  const buckets = {};
  /** @type {string[]} */
  const validatedBuckets = [];
  for (const [name, b] of Object.entries(cal.buckets ?? {})) {
    const ev = b?.edge_validation;
    if (!ev?.spread || !ev?.total) throw new ContentError(`bucket ${name} has no edge_validation`);
    buckets[name] = {
      n_games: b.n_games,
      stability_range: b.stability_range,
      margin_sd: b.margin_sd,
      spread: ev.spread,
      total: ev.total,
    };
    for (const market of ["spread", "total"]) {
      if (ev[market].validated === true) validatedBuckets.push(`${name} ${market}`);
    }
  }
  if (!Object.keys(buckets).length) throw new ContentError("calibration has no buckets");
  // The lowest input stability of any backtested game: the bottom of the lowest bucket's
  // stability_range. The game view dims context values below it (P6.md §5).
  const floors = Object.values(cal.buckets).map((b) => b?.stability_range?.[0]);
  if (!floors.every((f) => typeof f === "number" && f > 0 && f < 1)) {
    throw new ContentError("a calibration bucket has no stability_range in (0, 1)");
  }
  const fitSeasons = coefficients.fit_seasons;
  if (!Array.isArray(fitSeasons) || !fitSeasons.every(Number.isInteger)) {
    throw new ContentError("model_coefficients.json has no fit_seasons list");
  }
  const base = coefficients.spec?.name;
  const coef = (key) => {
    const c = coefficients.coefficients?.[key];
    if (typeof c?.value !== "number" || typeof c?.se !== "number") {
      throw new ContentError(`model_coefficients.json has no coefficient "${key}"`);
    }
    return { value: c.value, se: c.se };
  };
  if (typeof base !== "string") throw new ContentError("model_coefficients.json has no spec.name");

  return {
    model_version: coefficients.model_version,
    fit_seasons: fitSeasons,
    test_seasons: seasons,
    n_games: n,
    margin_mae: {
      model: number(all, "Model MAE", MARGIN),
      close: number(all, "Close MAE", MARGIN),
    },
    spread_edge_corr: {
      r: number(corrAll, "r", SPREAD_CORR),
      ci: interval(corrAll, "95% CI", SPREAD_CORR),
      n: number(corrAll, "n", SPREAD_CORR),
      validated: validatedCell === "yes",
    },
    validated_buckets: validatedBuckets,
    buckets,
    stability_floor: Math.min(...floors),
    model: {
      base,
      fitted_on: coefficients.fitted_on,
      n_games: coefficients.n_games,
      alpha: coef("alpha"),
      beta_off: coef(`beta_off:${base}`),
      beta_def: coef(`beta_def:${base}`),
      gamma: coef("gamma"),
    },
    report: reportProvenance(reportMd),
    win_rates: winRateBuckets(reportMd),
  };
}
